[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ringio = "JBhfRyHLDdTyGKz78hzeA26kKmtwd37PFkX3tvwmbmYy"

[programs.devnet]
ringio = "JBhfRyHLDdTyGKz78hzeA26kKmtwd37PFkX3tvwmbmYy"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[registry]
url = "https://api.apr.dev"
